### ISSUE TITLE
Reduce the overhead of algorithm executions

### ISSUE THREAD

**Issue by thorsten-papenbrock** [HPI-Information-Systems/Metanome#328]
Sometimes the overhead of algorithm executions exeeds the runtime of the algorithms by far. Hence, we must identify the reason for this and fix it.

"Der HyFD Algorithmus läuft ~40 Sekunden auf dem horse Datensatz:
~5 Sekunden Ausführung des Algorithmus
~15 Sekunden Aufräumungen nach der Algorithmus Ausführung (größtenteils Objekte in Hibernate speichern)
~20 Sekunden Ergebnisse wieder von Platte lesen, um sie anschließend anzeigen zu können"

The reason might be the parsing of results into JSON and back into Objects. If so, we should replace JSON by some more read- and write-efficient (maybe own) result format.

**Comment by tabergma** [comment]
The overhead comes from converting the results into JSON, writing it to disk, reading the JSON again and converting it into a result object again.
Therefore, we implemented a custom way of writing UCCs, INDs, FDs and ODs. This is a lot faster. All of these result types implement the two methods “toString” and “fromString”. Thereby, the columns are decoded by numbers, which are defined in a header.
For CUCCs and Basic Statistics we did not implement those methods. CUCCs are quite complicated, we would need a grammar for writing them to disk. Because we do not know what kind of columns the basic statistic result has, we also did not implemented for this result type.

There is still a little bit overhead by the creation of the new process and passing parameter via hibernate (store and retrieve). But this ‘overhead’ is necessary and can not be reduced.
