### ISSUE TITLE
how to run existing algorithm as project to edit them and again rebuild them

### ISSUE THREAD

**Issue by s1knd** [HPI-Information-Systems/Metanome#404]
I want make changing in normalization algorithm. i download it code from algorithm source code page. then i build as maven project in eclipse and got error in pom file. most of error are dependencies error. Can you help to provide full guide how to edit a algorithm and then again rebuild jar and run. Thanks

**Comment by thorsten-papenbrock** [comment]
Dear s1knd,

the guide on how to build the algorithms can be found in the Readme file of the algorithms page: 
https://github.com/HPI-Information-Systems/metanome-algorithms

Instructions on how to run the algorithms is available here:
https://hpi.de/naumann/projects/data-profiling-and-analytics/metanome-data-profiling/algorithms.html

To help you further, can you provide some more details about how you exactly tried to build the code? Did you follow the steps in the Readme file or what build did you try? What error did you get? Can you post the stack-trace here?

Best,
Thorsten

**Comment by s1knd** [comment]
Thank you much Thorsten for your reply.

i follow the step to build all algorithms and also get .jar file against all the algorithms.(But i did not use -Xmx1g -Xms20m -Xss10m parameters to build these algorithms )

I test all the algorithms they are working well and providing results. But Normalize algorithm jar file name is Normalize-1.2-SNAPSHOT is not working and giving error while uploading it to metanome.

Here i am explaining my problem step by step with images.

**1 image**: in this image you will see when i upload other algorithm it automatically generate author name and description about that algorithm and no problem comes when i save this algorithm.
link of image: https://imge.to/i/3lo61

**2 Image:** in this image i upload Normalize algorithm but it did not generate author name and description about that algorithm. you can see it in this image.
link of image: https://imge.to/i/3l6Sy

**3 image:** in this image when i named Normalize algorithm and click on save Button then that error will occure. An error occurred when saving this algorithm: HTTP 400 Bad Request
link of image: https://imge.to/i/3lmcx


I hope you will understand what i want to try to explain my problem. But their is one more thing to explain
But when i download old version of Normalize algorithm(Normi-1.1-SNAPSHOT jar file) from your website https://hpi.de/naumann/projects/data-profiling-and-analytics/metanome-data-profiling/algorithms.html
it work good and provide the author name and description automatically and also 
 when i click save it did not give any error and provide results.
here is the image: https://imge.to/i/3wfRY


So the point is i only need Normalization algorithm and want to make changing in it. for this purpose i need source code of  Normalization algorithm version 1.1  because 1.2 is not working. 

i checked all the commit on your algorithm source code page and i did not find source code of Normi-1.1-SNAPSHOT Only i find source code of Normalize-1.2-SNAPSHOT.

So help me to remove this error or provide source code of Normi-1.1-SNAPSHOT.
Thanks

**Comment by s1knd** [comment]
Sir its Urgent Kindly Help me please.

**Comment by thorsten-papenbrock** [comment]
Dear Sikander,

sorry for the late reply. With your descriptions, I was able to spot and remove the error: The algorithm was developed under the working title "Normi" that we later, i.e., after publication changed to "Normalize". That change was not made consistently so Metanome was still look for an entry class in a path that used the old "normi" label. I fixed that bug in the code on GitHub and on the algorithms page.

The reason why this mistake was not seen since the renaming change is that you can run the algorithm also in interactive mode outside the Metanome framework. Simply run `java -jar Normailze.jar` and the algorithm will start.

If you run the algorithm stand-alone, have a look into the Config class and specify the input dataset there:
https://github.com/HPI-Information-Systems/metanome-algorithms/blob/master/Normalize/src/main/java/de/metanome/algorithms/normalize/config/Config.java

I know these parameters should better be algorithm parameters for the `java -jar Normailze.jar` call and not hard-coded variables that force a re-build of the algorithm for every experiment, but time was running out back then so we did not implement that properly.

Please feel free to change and edit the algorithm in any way you want. The entry point for the algorithm is `de.metanome.algorithms.normi.Main`. Unfortunately, Normalize is one of our worst-maintained algorithm and you will find lots of experimental and testing code in it. I apologize a lot for that and we will take better care of it as soon as we can.

Many thanks though for reporting the bug. I hope your research in this direction works our. Please don't hesitate to contact me via email if you have any further questions. I will close that ticket now, because I the  error should be fixed now.

Best,
Thorsten

**Comment by s1knd** [comment]
Hello Sir,

Again I need your help and I know you will not disappoint Me.

Its about Normalization algorithm. I do a lot of research to understand
that algorithm because i need one change in it. Change is not too big its a
very small. kindly read the attached file in which i explain everything
very well and you will able to understand what change i want in algorithm.

Sir its very very humble request to you please make this change and send me
Source code. I know its not big change its very small but the reason behind
Why i am asking you for make change.  Because I try many method and
different logic to get this change but i am not able to run it in eclipse
as project to check error in it every i make any change. If a want to run
in eclipse I need to change input file taking code and showing result
code(i think these changing are require may be i wrong).

So whenever i make any change in it i build jar file every time and test it
into metanome. But did not provide error detail. I try a lot of time but
now i am running out of time and did not have much time for more
experiment. That is why i connecting to you and also i know this not you
work But i am begging to you Sir kindly made this small change please.

Again i am saying its humble request To You Sir Please.

Waiting for your reply desperately.
